//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appoint
    {
        public int id { get; set; }
        public Nullable<int> tutor_id { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public string is_deleted { get; set; }
        public Nullable<int> student_appoint_id { get; set; }
        public Nullable<int> semester_id { get; set; }
        public Nullable<int> course_code_id { get; set; }
    
        public virtual tutor tutor { get; set; }
        public virtual course_codes course_codes { get; set; }
        public virtual semester_previous semester_previous { get; set; }
        public virtual students_appoint students_appoint { get; set; }
    }
}
