//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_codes
    {
        public course_codes()
        {
            this.appoints = new HashSet<appoint>();
            this.students_appoint = new HashSet<students_appoint>();
        }
    
        public int id { get; set; }
        public string courseCode { get; set; }
        public Nullable<int> section_id { get; set; }
    
        public virtual ICollection<appoint> appoints { get; set; }
        public virtual section_region section_region { get; set; }
        public virtual ICollection<students_appoint> students_appoint { get; set; }
    }
}
