//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items_region
    {
        public items_region()
        {
            this.rooms_region = new HashSet<rooms_region>();
        }
    
        public int item_ID { get; set; }
        public string item_name { get; set; }
        public int item_total { get; set; }
        public string item_remarks { get; set; }
        public string is_deleted { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public string district { get; set; }
    
        public virtual ICollection<rooms_region> rooms_region { get; set; }
    }
}
