//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_Applicata_DataBaseEntities1 : DbContext
    {
        public test_Applicata_DataBaseEntities1()
            : base("name=test_Applicata_DataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tutor_experience> tutor_experience { get; set; }
        public DbSet<tutor_qualification> tutor_qualification { get; set; }
        public DbSet<tutor> tutors { get; set; }
        public DbSet<user_roles> user_roles { get; set; }
        public DbSet<user> users { get; set; }
    }
}
