//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms_region
    {
        public int room_ID { get; set; }
        public int room_no { get; set; }
        public int item_ID { get; set; }
        public int item_amount { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public string dstrict { get; set; }
    
        public virtual items_region items_region { get; set; }
    }
}
