//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section_region
    {
        public section_region()
        {
            this.course_codes = new HashSet<course_codes>();
            this.section_tutors = new HashSet<section_tutors>();
            this.semester_previous = new HashSet<semester_previous>();
            this.semester_current = new HashSet<semester_current>();
            this.users = new HashSet<user>();
        }
    
        public int section_id { get; set; }
        public string name { get; set; }
        public string incharge { get; set; }
    
        public virtual ICollection<course_codes> course_codes { get; set; }
        public virtual ICollection<section_tutors> section_tutors { get; set; }
        public virtual ICollection<semester_previous> semester_previous { get; set; }
        public virtual ICollection<semester_current> semester_current { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
