//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section_tutors
    {
        public int sec_tutor_id { get; set; }
        public string sr_no { get; set; }
        public int tutor_id { get; set; }
        public int section_id { get; set; }
        public string students { get; set; }
        public string appoint_status { get; set; }
        public Nullable<int> semester_id { get; set; }
        public string course_code { get; set; }
    
        public virtual section_region section_region { get; set; }
        public virtual tutor tutor { get; set; }
        public virtual semester_previous semester_previous { get; set; }
    }
}
