//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semester_current
    {
        public int id { get; set; }
        public string semester { get; set; }
        public string year_ { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public Nullable<int> section_id { get; set; }
    
        public virtual section_region section_region { get; set; }
    }
}
