//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_appoint
    {
        public students_appoint()
        {
            this.appoints = new HashSet<appoint>();
        }
    
        public int id { get; set; }
        public string roll_no { get; set; }
        public string sex { get; set; }
        public string status_appoint { get; set; }
        public string program { get; set; }
        public Nullable<int> student_id { get; set; }
        public string updated_by { get; set; }
        public string updated_date { get; set; }
        public string is_deleted { get; set; }
        public Nullable<int> semester_id { get; set; }
        public Nullable<int> courseCode_id { get; set; }
    
        public virtual ICollection<appoint> appoints { get; set; }
        public virtual course_codes course_codes { get; set; }
        public virtual semester_previous semester_previous { get; set; }
        public virtual students_region students_region { get; set; }
    }
}
