//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutor
    {
        public tutor()
        {
            this.appoints = new HashSet<appoint>();
            this.section_tutors = new HashSet<section_tutors>();
            this.tutor_experience = new HashSet<tutor_experience>();
            this.tutor_qualification = new HashSet<tutor_qualification>();
        }
    
        public int tutor_id { get; set; }
        public string name { get; set; }
        public string f_name { get; set; }
        public string reg_no { get; set; }
        public string designation { get; set; }
        public string basic_pay_scale { get; set; }
        public string official_add { get; set; }
        public string mail_add { get; set; }
        public string qulification { get; set; }
        public string phone { get; set; }
        public string district { get; set; }
        public string tehsil { get; set; }
        public string gender { get; set; }
        public string image_profile { get; set; }
        public string image_updation_form { get; set; }
        public string t_status { get; set; }
        public string srNo { get; set; }
        public string intelCertificate { get; set; }
        public string update_by { get; set; }
        public string update_date { get; set; }
    
        public virtual ICollection<appoint> appoints { get; set; }
        public virtual ICollection<section_tutors> section_tutors { get; set; }
        public virtual ICollection<tutor_experience> tutor_experience { get; set; }
        public virtual ICollection<tutor_qualification> tutor_qualification { get; set; }
    }
}
