//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDangular_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tutor_experience
    {
        public int e_id { get; set; }
        public string institute { get; set; }
        public string class_level { get; set; }
        public string subject_taught { get; set; }
        public string duration { get; set; }
        public string if_past_at_aiou { get; set; }
        public string course_codes { get; set; }
        public int tutor_id { get; set; }
        public string update_date { get; set; }
        public string update_by { get; set; }
        public string is_deleted { get; set; }
    
        public virtual tutor tutor { get; set; }
    }
}
